apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: message-service-monitor
spec:
  selector:
    matchLabels:
      app: message-service
  endpoints:
  - port: 5000
    path: /metrics
